### ISSUE TITLE
Issue during reorder: Concurrent modification during iteration: Instance(length:0) of '_GrowableList'.

### ISSUE THREAD

**Issue by bondarevdev** [DavideBelsole/great_list_view#13]
Hi, i have tried to run example and i am getting error on lattest verios 0.1.3:

```
======== Exception caught by widgets library =======================================================
The following ConcurrentModificationError was thrown while rebuilding dirty elements:
Concurrent modification during iteration: Instance(length:0) of '_GrowableList'.

The relevant error-causing widget was: 
  AutomaticAnimatedListView<ItemData> AutomaticAnimatedListView:file:///home/dimka/ttt/great_list_view/example/lib/main.dart:56:14
When the exception was thrown, this was the stack: 
#0      ListIterator.moveNext (dart:_internal/iterable.dart:336:7)
#1      AnimatedSliverMultiBoxAdaptorElement.performRebuild (package:great_list_view/src/core/child_manager.dart:145:45)
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#12     _invoke (dart:ui/hooks.dart:150:10)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#14     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
The element being rebuilt at the time was index 0 of 1: AnimatedSliverList
  dependencies: [_ScrollableScope, _EffectiveTickerMode]
  renderObject: AnimatedRenderSliverList#c1b64 relayoutBoundary=up2 NEEDS-LAYOUT
====================================================================================================

```

**Comment by DavideBelsole** [comment]
Try the new version 0.1.4.
Thanks
