### ISSUE TITLE
Breaks LayoutBuilder

### ISSUE THREAD

**Issue by pingbird** [DavideBelsole/great_list_view#31]
Using a LayoutBuilder in AnimatedListView's itemBuilder results in an exception during layout:

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/object.dart': Failed assertion: line 1027 pos 12: '_debugDoingLayout': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  LayoutBuilder LayoutBuilder:file:///home/ping/IdeaProjects/ftest_bean/lib/main_paint_layout_error2.dart:50:20
When the exception was thrown, this was the stack: 
#2      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1027:12)
#3      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2246:14)
#4      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228:7)
#5      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:316:5)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#7      RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#10     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#13     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#15     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:552:11)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#17     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#19     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1467:11)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#21     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:249:12)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#24     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
#27     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
#28     AnimatedRenderSliverList.measureItem.<anonymous closure> (package:great_list_view/src/sliver_list.dart:1013:17)
#29     AnimatedSliverMultiBoxAdaptorElement.disposableElement.<anonymous closure> (package:great_list_view/src/child_manager.dart:653:16)
#30     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2523:15)
#31     AnimatedSliverMultiBoxAdaptorElement.disposableElement (package:great_list_view/src/child_manager.dart:647:12)
#32     AnimatedRenderSliverList.measureItem (package:great_list_view/src/sliver_list.dart:1012:18)
#33     AnimatedRenderSliverList.measureItems.<anonymous closure> (package:great_list_view/src/sliver_list.dart:999:17)
(elided 7 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: _RenderLayoutBuilder#7498c relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=1264.0, 0.0<=h<=Infinity)
...  size: MISSING
RenderObject: _RenderLayoutBuilder#7498c relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1264.0, 0.0<=h<=Infinity)
  size: MISSING
====================================================================================================
```

```dart
import 'package:flutter/material.dart';
import 'package:great_list_view/great_list_view.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final listController = AnimatedListController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('LayoutBuilder crash'),
        actions: [
          IconButton(
            onPressed: () {
              listController.notifyInsertedRange(0, 1);
            },
            icon: const Icon(Icons.add),
          ),
        ],
      ),
      body: AnimatedListView(
        listController: listController,
        itemBuilder: (context, index, data) {
          return Card(
            margin: const EdgeInsets.all(8),
            child: LayoutBuilder(builder: (context, constraints) {
              return Row(
                children: [
                  const Icon(Icons.note),
                  Center(child: Text("index $index")),
                ],
              );
            }),
          );
        },
        initialItemCount: 0,
      ),
    );
  }
}
```

Related: https://github.com/PixelToast/boxy/issues/20

**Comment by wenyue** [comment]
I have the same issue
