### ISSUE TITLE
Console throw exception when call `controller.dispatchNewList(...)` to update an item in list

### ISSUE THREAD

**Issue by bahung1221** [DavideBelsole/great_list_view#8]
Hi, 

Like the title, when I call `controller.dispatchNewList(...)` to update one item in the current list view, the below exception was thrown on the console, the app still working just like normal. So I don't know is this important or not.

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
'package:flutter/src/rendering/layer.dart': Failed assertion: line 270 pos 12: '!_debugDisposed': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  MorphTransition
  MorphTransition:file:///Users/macbookair/Workspace/Personal/todolist/lib/utils/task_animated_list.dart:63:12

When the exception was thrown, this was the stack:
#2      Layer.markNeedsAddToScene (package:flutter/src/rendering/layer.dart:270:12)
#3      OpacityLayer.alpha= (package:flutter/src/rendering/layer.dart:1882:7)
#4      PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:617:9)
```

Thanks a lot 🍻

**Comment by DavideBelsole** [comment]
Please, migrate to the new version (0.1.0) and let me know if the issue persists.
